service: aws-serverless-example
frameworkVersion: '2'
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1
  stage: ${opt:stage,'dev'}  

functions:
  hello:
    handler: functions/example.handler
    events:
      - httpApi:
          path: /example
          method: get
